### PR TITLE
Feature/cmts diagrams

### PR DESCRIPTION
**Pull request by olebowle**

### CODE REVIEW

**Comment by schmto** [comment]
i don't get the point: how is the cluster specific association done? or is it straight forward: showing "only" all cacti diagrams?

**Comment by olebowle** [comment]
Please have a look at line [921](https://github.com/nmsprime/nmsprime/pull/271/files#diff-d1d836e801b339c474d91d3cf0299b28R921) and line [934](https://github.com/nmsprime/nmsprime/pull/271/files#diff-d1d836e801b339c474d91d3cf0299b28R934). First I get all the indices of the netelement in question and filter for those in the cacti db.

**Comment by schmto** [comment]
ah, cool. which means: it's a combination of netelement linking AND generic SNMP GUI module(?). Correct? Then i got the point.

**Comment by schmto** [comment]
more than perfect approach :+1:

**Pull request merged**
